# Generated by Django 2.2.1 on 2019-06-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todoitem',
            new_name='tditem',
        ),
        migrations.RenameModel(
            old_name='todolist',
            new_name='tdlist',
        ),
    ]
