# Generated by Django 2.2.1 on 2019-06-09 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20190609_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='tditem',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.tdlist'),
            preserve_default=False,
        ),
    ]
