# Generated by Django 2.2.1 on 2019-06-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_tditem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tditem',
            old_name='name',
            new_name='todolist',
        ),
    ]
